import type { NextPage } from "next";
import Head from "next/head";
import { ThemeProvider } from "styled-components";
import { GlobalStyles, theme } from "../styles";

const Home: NextPage = () => {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyles />
        <Head>
          <title>Next Sudoku</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <span>Raules Ezinha :sunglasses:</span>
        </main>
    </ThemeProvider>
  );
};

export default Home;
